# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3bc841797233b74cfeafe2edb206e388"
name = "bharath-cyces"
handle = "bharath-cyces"
application_url = "https://database-vaccine-returns-mission.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = ["https://database-vaccine-returns-mission.trycloudflare.com/auth/callback", "https://database-vaccine-returns-mission.trycloudflare.com/auth/shopify/callback", "https://database-vaccine-returns-mission.trycloudflare.com/api/auth/callback"]

[pos]
embedded = false
